name: Docker Build and Push

on:
  schedule:
    - cron: '0 11 * * *'
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_IMAGE_REGISTRY }}
          username: ${{ vars.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build Docker Images
        run: |
          VARIANTS=("typescript-node" "javascript-node" "node")
          for VARIANT in "${VARIANTS[@]}"; do
            echo "Building and pushing $VARIANT image..."
            chmod +x ./build.sh && ./build.sh "$VARIANT"
          done
        env:
          DOCKER_REGISTRY_USER: ${{ vars.DOCKER_REGISTRY_USER }}

      - name: Push Docker Images
        run: |
          docker push --all-tags "${DOCKER_REGISTRY_USER}/gemini-cli"
        env:
          DOCKER_REGISTRY_USER: ${{ vars.DOCKER_REGISTRY_USER }}
